
version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:2020.01
  macos: # macos are not supported in free version of circle-ci
    macos:
      xcode: 10.1

jobs:
  test:
    parameters:
      os:
        type: executor
      test_script:
        type: string
      bazel_version:
        type: string
    executor: << parameters.os >>
    environment:
      TEST_SCRIPT: << parameters.test_script >>
      XDG_CACHE_HOME: ~/xdg_cache
      USE_BAZEL_VERSION: << parameters.bazel_version >>
    steps:
      - checkout
      - run: |-
              SYS_ENV_PLATFORM=linux
              if uname -a | grep Darwin; then
                SYS_ENV_PLATFORM=darwin
              fi
              # Set environment variables
              # Install Bazelisk
              sudo wget -O /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-${SYS_ENV_PLATFORM}-amd64
              sudo chmod +x /usr/local/bin/bazel
              
              cat .bazelrc.travis >> .bazelrc #TODO: rename .travis to .ci
              # Execute bazel
              bash ./${TEST_SCRIPT}.sh ci

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              os: [linux]
              bazel_version: ["2.0.0", "3.4.1" ]
              test_script: ["test_rules_scala", "test_reproducibility", "test_version"]

